[package]
name = "device"
version = "0.0.0"
edition = "2024"
license = "CC0-1.0"
description = "Generative device."

[dependencies]
nalgebra.workspace = true
serde.workspace = true
strum.workspace = true
